image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x ./gradlew
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose -f ./docker-compose-mysql.ci.yml up --build -d
  - sleep 30
  - sudo java -Dspring.credit-gate.url=http://localhost:9999/credit -Dspring.payment-gate.url=http://localhost:9999/payment -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass -jar ./aqa-shop.mysql/aqa-shop.jar &
  - sleep 30
  - sudo curl localhost:8080
build_script:
  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true -Ddb.url=jdbc:mysql://host.docker.internal:3306/app --info --tests StartPageCiTest
