#image: Ubuntu  # образ для сборки
#image: Visual Studio 2019

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x ./gradlew
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - choco install docker-compose
  #- sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - docker-compose -f ./docker-compose-mysql.yml up -d
  - docker logs gate-simulator
  - docker logs aqa-shop-postgres

build_script:
  # запускаем тест, флаг --info позволяет выводить больше информации
  - ./gradlew test -Dselenide.headless=true -Ddb.url=jdbc:mysql://host.docker.internal:3306/app