version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  gate:
    container_name: gate-simulator
    build: ./gate-simulator
    image: gate-simulator:1.0
    ports:
      - '9999:9999'
    restart: on-failure
  aqa-shop:
    container_name: aqa-shop-mysql
    build: ./aqa-shop.mysql
    image: aqa-shop-mysql:1.0
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mysql
      - gate
