version: '3.7'
services:
#  postgres:
#   image: postgres:12-alpine
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=pass  
  mysql:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: .
    image: gate-simulator:1.0
    ports:
      - '9999:9999'
 