# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-mysql.yml up --build -d
    - name: Check running containers
      run: docker ps -a
    - name: Wait for containers start
      run: sleep 30
    - name: Update repository
      run: sudo apt-get update
    - name: Install net-tools
      run: sudo apt-get install net-tools
    - name: Check for aqa-shop's port (container)
      run: netstat -ltnp | grep -w ':8080'
    - name: Hands start app
      run: java -jar ./aqa-shop.mysql/aqa-shop.jar &
    - name: Wait for containers start
      run: sleep 30
    - name: Check for aqa-shop's port (hands run)
      run: netstat -ltnp | grep -w ':8080'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test -Dselenide.headless=true -Ddb.url=jdbc:mysql://host.docker.internal:3306/app --info --tests StartPageCiTest
