# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-postgres.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs gate-simulator
      run: docker logs gate-simulator
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check logs aqa-shop-postgres
      run: docker logs aqa-shop-postgres
    - name: Build with Gradle
      run: ./gradlew test -Dselenide.headless=true -Ddb.url=jdbc:postgresql://host.docker.internal:5432/app
    - name: Check logs aqa-shop-postgres
      run: docker logs aqa-shop-postgres

